name: Lint Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Replace with your Node.js version if different

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          echo "Running ESLint..."
          npx eslint . --fix || (echo "❌ Linting failed. Fix the errors before committing." && exit 1)

      - name: Lint Success Message
        if: success()
        run: echo "✅ ESLint passed with no errors."
